import mongoose from 'mongoose';
import 'dotenv/config';
import Product from './models/Product.js';
import Category from './models/Category.js';
import Review from './models/Review.js';
import products from '../src/data/products.json' assert { type: 'json' };
import categories from '../src/data/categories.json' assert { type: 'json' };
import reviews from '../src/data/reviews.json' assert { type: 'json' };

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB connected for seeding');

    await Product.deleteMany({});
    await Category.deleteMany({});
    await Review.deleteMany({});

    console.log('Cleared existing data');

    await Category.insertMany(categories);
    console.log('Categories seeded');

    // For products, we don't need to do anything special yet,
    // but for reviews, we need to associate them with the newly created products.
    // Since the product IDs from the JSON file are not the same as the ones generated by MongoDB,
    // we will handle this in a more advanced way later if needed.
    // For now, we will just insert the products.

    await Product.insertMany(products);
    console.log('Products seeded');

    // A more complex logic would be needed here to map old product IDs to new ones for reviews
    // For now, we are skipping seeding reviews as they are linked to products.
    await Review.insertMany(reviews);
    console.log('Reviews seeded');


    console.log('Database seeding complete');
  } catch (error) {
    console.error('Seeding error:', error);
  } finally {
    mongoose.disconnect();
    console.log('MongoDB disconnected');
  }
};

seedDatabase();
